FROM ubuntu:16.04
ENV http_proxy ${http_proxy}
ENV https_proxy ${https_proxy}

RUN apt-get update && apt-get install -y \
    openjdk-8* \
    maven \
    maven* \
    python-pip \
    python-dev \
    build-essential \
    libffi-dev \
    libssl-dev \
    subversion \
    git \
    npm

RUN pip install fabric
RUN npm install -g node-qunit-phantomjs

COPY ./ /opt/app/
COPY ./searchcode.sqlite.empty /opt/app/searchcode.sqlite
COPY ./searchcode.properties.example /opt/app/searchcode.properties
WORKDIR /opt/app/
RUN fab test
